name: Release SDKs

on:
  push:
    tags:
      - 'v*.*.*'  # Run workflow on version tags, e.g. v1.0.0

jobs:
  release-node:
    name: Release Node.js SDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdks/node-sdk
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release-python:
    name: Release Python SDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdks/python-sdk
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build package
        run: python -m build
      - name: Publish to PyPI
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

  release-rust:
    name: Release Rust SDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdks/rust-sdk
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Publish to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path sdks/rust-sdk/Cargo.toml --token ${{ secrets.CRATES_IO_TOKEN }}

  create-release:
    name: Create GitHub Release
    needs: [release-node, release-python, release-rust]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Extract version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Get release notes
        id: release_notes
        run: |
          if [ -f RELEASE_NOTES.md ]; then
            # Use the pre-generated release notes if available
            RELEASE_NOTES=$(cat RELEASE_NOTES.md)
          else
            # Extract notes from CHANGELOG.md for this version
            RELEASE_NOTES=$(awk -v version="$VERSION" '
              BEGIN { found=0; output=0; }
              /^## \['"$VERSION"'\]/ { found=1; output=1; }
              /^## \[[0-9]+\.[0-9]+\.[0-9]+\]/ && !/^## \['"$VERSION"'\]/ { if (found) output=0; }
              { if (output) print; }
            ' CHANGELOG.md)
            
            # Add package links
            RELEASE_NOTES="${RELEASE_NOTES}
            
            ## Available Packages
            
            - **Node.js**: \`npm install vaultarq-node@$VERSION\`
            - **Python**: \`pip install vaultarq==$VERSION\`
            - **Rust**: Add \`vaultarq = \"$VERSION\"\` to your \`Cargo.toml\`
            - **Go**: \`go get github.com/Vaultarq/vaultarq/sdks/go-sdk@v$VERSION\`"
          fi
          
          # Convert to single line with newline escapes for GitHub Actions
          RELEASE_NOTES="${RELEASE_NOTES//'%'/'%25'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\n'/'%0A'}"
          RELEASE_NOTES="${RELEASE_NOTES//$'\r'/'%0D'}"
          echo "NOTES=$RELEASE_NOTES" >> $GITHUB_ENV
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: ${{ env.NOTES }} 